### ISSUE TITLE
AttributeError: module lazy_ has no attribute omni

### ISSUE THREAD

**Issue by zhucoffee** [cremebrule/digital-cousins#1]
Thank you for your wonderful work!

I am encountering an AttributeError when attempting to launch the OmniGibson simulator in my project. Below is the relevant traceback of the error:

`
Traceback (most recent call last):
  File "/home/admin01/acdc/digital-cousins/digital_cousins/pipeline/acdc.py", line 202, in <module>
    main(args)
  File "/home/admin01/acdc/digital-cousins/digital_cousins/pipeline/acdc.py", line 170, in main
    pipeline.run(
  File "/home/admin01/acdc/digital-cousins/digital_cousins/pipeline/acdc.py", line 158, in run
    success, step_3_output_path = step_3(
  File "/home/admin01/acdc/digital-cousins/digital_cousins/pipeline/generation.py", line 188, in __call__
    og.launch()
  File "/home/admin01/acdc/digital-cousins/deps/OmniGibson/omnigibson/simulator.py", line 246, in _launch_simulator
    og.app = _launch_app()
  File "/home/admin01/acdc/digital-cousins/deps/OmniGibson/omnigibson/simulator.py", line 148, in _launch_app
    with launch_context(None):
  File "/home/admin01/anaconda3/envs/acdc/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/admin01/acdc/digital-cousins/deps/OmniGibson/omnigibson/utils/ui_utils.py", line 171, in suppress_omni_log
    log = lazy.omni.log.get_log()
  File "/home/admin01/acdc/digital-cousins/deps/OmniGibson/omnigibson/utils/lazy_import_utils.py", line 29, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}") from None
AttributeError: module lazy_ has no attribute omni
`
Current Directory Structure:

Here is the directory structure of my project for your reference (Partially):
> /home/admin01/acdc/digital-cousins/
> ├── deps/
> │   └── OmniGibson/
> │       └── [OmniGibson files]
> └── digital_cousins/
>     └── pipeline/
>         ├── acdc.py

Additional Information:

I have verified that the Isaac Sim path is set up correctly, and I can connect to Isaac Sim successfully from another Conda environment.
`
echo $ISAAC_PATH
/home/admin01/.local/share/ov/pkg/isaac-sim-4.1.0
`
I would appreciate any guidance on resolving this issue. Thank you!

**Comment by cremebrule** [comment]
Hi @zhucoffee ,

Thanks for raising this issue! Can  you verify that OmniGibson can be imported directly? eg:

```python
import omnigibson as og
og.launch()
og.shutdown()
```

**Comment by cremebrule** [comment]
Thanks for the additional details.  Hmmmm this is a bit surprising. We haven't actually tested the Launcher install, so perhaps that might be the issue?

Can you try installing OmniGibson without the `--launcher-install` flag and see if that works? You may need to create a new conda env.

**Comment by cremebrule** [comment]
I will close this issue for now. Feel free to reopen if any issues persist!
