### ISSUE TITLE
KeyError in collect demos

### ISSUE THREAD

**Issue by andyaloha** [cremebrule/digital-cousins#10]
Thanks for your great work.
When I run examples/1_collect_demos.py exactly as the example usage, I encountered the following error. How can I resolve this?

python 1_collect_demos.py \
--scene_path ../tests/acdc_output/step_3_output/scene_0/scene_0_info.json \
--target_obj cabinet_4 \
--target_link link_1 \
--cousins bottom_cabinet,bamfsz,link_1 bottom_cabinet_no_top,vdedzt,link_0 \
--dataset_path test_demos.hdf5 \
--n_demos_per_model 3 \
--eval_cousin_id 0 \
--seed 0

Traceback (most recent call last):
  File "/data/gaofei/simulator/OmniGibson/tools/code/digital-cousins/examples/1_collect_demos.py", line 295, in <module>
    main(args)
  File "/data/gaofei/simulator/OmniGibson/tools/code/digital-cousins/examples/1_collect_demos.py", line 207, in main
    env = EnvOmniGibson(
  File "/data/gaofei/simulator/OmniGibson/tools/code/digital-cousins/digital_cousins/envs/robomimic/env_og.py", line 361, in __init__
    self.env = create_wrapper(env=self.env)
  File "/data/gaofei/simulator/OmniGibson/OmniGibson/omnigibson/envs/env_wrapper.py", line 21, in create_wrapper
    return create_class_from_registry_and_config(
  File "/data/gaofei/simulator/OmniGibson/OmniGibson/omnigibson/utils/python_utils.py", line 286, in create_class_from_registry_and_config
    return cls(**cls_kwargs)
  File "/data/gaofei/simulator/OmniGibson/tools/code/digital-cousins/digital_cousins/envs/omnigibson/cabinet_open_wrapper.py", line 280, in __init__
    link = cab.links[cab_link]
KeyError: 'link_1'

It seems that the cabinet_4 has no 'link_1'. The keys of its links are ['base_link', 'door1', 'glass1', 'door2', 'glass2'] as I print it.

**Comment by cremebrule** [comment]
To add to @RogerDAI1217 's point above, make sure you select the link that actually has the handle attached to it -- likely `door1` or `door2`!

**Comment by andyaloha** [comment]
@RogerDAI1217 @cremebrule Thanks! I have solved this problem by switching scene_0 to scene_2 where the cabinet_4 has 'link_1'.
