### ISSUE TITLE
no load_state_dict

### ISSUE THREAD

**Issue by xuxumiao777** [cremebrule/digital-cousins#17]
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "/data/yanxu/.conda/envs/acdc/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    return self._get_impl(
  File "/data/yanxu/.conda/envs/acdc/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 444, in _get_impl
    node = self._get_child(
  File "/data/yanxu/.conda/envs/acdc/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/data/yanxu/.conda/envs/acdc/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 482, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key load_state_dict

**Comment by cremebrule** [comment]
Hi @xuxumiao777 ,

Hmmm I just did a fresh install of our repository and ran all of our tests, which seemed to work. Can you provide a repro script of what you ran?

**Comment by Snowflake-Pink** [comment]
![image](https://github.com/user-attachments/assets/35e18ffe-1a16-49c2-8aa8-859284add10d)

A similar issue of sam2. I'm not familar with sam2, and I would appeciate it if you could help me find the direction of the problem!

I have checked the MD5 of models in checkpoints folder.

**Comment by Snowflake-Pink** [comment]
I fixed it by copy sam2/configs
/sam2/sam2_hiera_l.yaml to overwrite sam2/sam2_hiera_l.yaml (the Symbolic Link). 😐😐

I don't know why this link doesn't work. The only extra action I did is `chmod -R 777 digital-cousins` (All files of digital-cousins).

**Comment by cremebrule** [comment]
Hi @Snowflake-Pink ,

Hmmm this is strange. So it works when you manually copy the raw file to overwrite the symbolic link within the SAM2 repo? We haven't run into any issue like this locally but it seems multiple users have, which makes me wonder whether it's a specific machine setup issue. Can you print out `conda list` to show all of your installed package versions?

**Comment by Snowflake-Pink** [comment]
> Hi @Snowflake-Pink ,
> 
> Hmmm this is strange. So it works when you manually copy the raw file to overwrite the symbolic link within the SAM2 repo? We haven't run into any issue like this locally but it seems multiple users have, which makes me wonder whether it's a specific machine setup issue. Can you print out `conda list` to show all of your installed package versions?

Of course. There is the conda list:
```
# packages in environment at /root/miniconda3/envs/acdc:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aenum                     3.1.15                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
albucore                  0.0.20                   pypi_0    pypi
albumentations            1.4.21                   pypi_0    pypi
altair                    5.5.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.6.2.post1              pypi_0    pypi
archspec                  0.2.3              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
asttokens                 2.4.1                    pypi_0    pypi
attrs                     24.2.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bddl                      3.5.0                    pypi_0    pypi
beautifulsoup4            4.12.3          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blinker                   1.9.0                    pypi_0    pypi
boltons                   23.0.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
boto3                     1.35.70                  pypi_0    pypi
botocore                  1.35.70                  pypi_0    pypi
brotli-python             1.0.9           py310h6a678d5_8    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bzip2                     1.0.8                h5eee18b_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
c-ares                    1.19.1               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2024.9.24            h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2024.8.30       py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.17.1          py310h1fdaa30_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
chardet                   4.0.0           py310h06a4308_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
charset-normalizer        3.3.2              pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
click                     8.1.7           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
clip                      1.0                      pypi_0    pypi
cloudpickle               3.1.0                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
conda                     24.11.0         py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-build               24.11.2         py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-index               0.5.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-libmamba-solver     24.9.0             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-package-handling    2.4.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-package-streaming   0.11.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
configargparse            1.7                      pypi_0    pypi
contourpy                 1.3.1                    pypi_0    pypi
cryptography              41.0.7                   pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cycler                    0.12.1                   pypi_0    pypi
dash                      2.18.2                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
diffusers                 0.31.0                   pypi_0    pypi
digital-cousins           0.0.1                     dev_0    <develop>
distro                    1.9.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
egl-probe                 1.0.2                    pypi_0    pypi
eval-type-backport        0.2.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
faiss-gpu                 1.8.0           py3.10_hedc54c9_0_cuda11.4.4    pytorch
farama-notifications      0.0.4                    pypi_0    pypi
fastapi                   0.115.5                  pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.13.1          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
flask                     3.0.3                    pypi_0    pypi
fmt                       9.1.0                hdb19cb5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
fonttools                 4.55.0                   pypi_0    pypi
fpsample                  0.3.3                    pypi_0    pypi
frozendict                2.4.2           py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
fsspec                    2024.10.0                pypi_0    pypi
ftfy                      6.3.1                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gradio                    4.29.0                   pypi_0    pypi
gradio-client             0.16.1                   pypi_0    pypi
gradio-imageslider        0.0.20                   pypi_0    pypi
groundingdino             0.1.0                     dev_0    <develop>
grpcio                    1.68.0                   pypi_0    pypi
gymnasium                 1.0.0                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
httpcore                  1.0.7                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.26.2                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
icu                       73.1                 h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
idna                      3.7             py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
imageio                   2.33.1                   pypi_0    pypi
imageio-ffmpeg            0.4.9                    pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
iopath                    0.1.10                   pypi_0    pypi
ipython                   8.20.0                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
isaacsim                  4.1.0.0                  pypi_0    pypi
isaacsim-app              4.1.0.0                  pypi_0    pypi
isaacsim-asset            4.1.0.0                  pypi_0    pypi
isaacsim-benchmark        4.1.0.0                  pypi_0    pypi
isaacsim-code-editor      4.1.0.0                  pypi_0    pypi
isaacsim-core             4.1.0.0                  pypi_0    pypi
isaacsim-cortex           4.1.0.0                  pypi_0    pypi
isaacsim-example          4.1.0.0                  pypi_0    pypi
isaacsim-extscache-kit    4.1.0.0                  pypi_0    pypi
isaacsim-extscache-kit-sdk 4.1.0.0                  pypi_0    pypi
isaacsim-extscache-physics 4.1.0.0                  pypi_0    pypi
isaacsim-gui              4.1.0.0                  pypi_0    pypi
isaacsim-kernel           4.1.0.0                  pypi_0    pypi
isaacsim-replicator       4.1.0.0                  pypi_0    pypi
isaacsim-rl               4.1.0.0                  pypi_0    pypi
isaacsim-robot            4.1.0.0                  pypi_0    pypi
isaacsim-robot-motion     4.1.0.0                  pypi_0    pypi
isaacsim-robot-setup      4.1.0.0                  pypi_0    pypi
isaacsim-ros1             4.1.0.0                  pypi_0    pypi
isaacsim-ros2             4.1.0.0                  pypi_0    pypi
isaacsim-sensor           4.1.0.0                  pypi_0    pypi
isaacsim-storage          4.1.0.0                  pypi_0    pypi
isaacsim-template         4.1.0.0                  pypi_0    pypi
isaacsim-test             4.1.0.0                  pypi_0    pypi
isaacsim-utils            4.1.0.0                  pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.2                   pypi_0    pypi
jinja2                    3.1.4           py310h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonpatch                 1.33            py310h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jsonpointer               2.1                pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jsonschema                4.23.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jsonschema-specifications 2023.7.1        py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
jupytext                  1.16.4                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
krb5                      1.20.1               h143b758_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libarchive                3.7.4                hfab0078_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libcublas                 11.11.3.6                     0    nvidia
libcurl                   8.9.1                h251f7ec_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libedit                   3.1.20230828         h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libev                     4.33                 h7f8727e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libfaiss                  1.8.0           h5aaf3ed_0_cuda11.4.4    pytorch
libffi                    3.4.4                h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
liblief                   0.12.3               h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libmamba                  1.5.8                hfe524e5_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libmambapy                1.5.8           py310h2dafd23_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libnghttp2                1.57.0               h2d74bed_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libsolv                   0.7.24               he621ea3_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libssh2                   1.11.0               h251f7ec_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuuid                   1.41.5               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libxml2                   2.13.5               hfdd30dd_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lz4-c                     1.9.4                h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3           py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mdit-py-plugins           0.4.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
menuinst                  2.2.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl                       2023.1.0         h213fc3f_46344    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0           py310h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.11          py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.2.8           py310h1128e8f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
more-itertools            10.3.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mpmath                    1.3.0                    pypi_0    pypi
narwhals                  1.14.2                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nest-asyncio              1.5.9                    pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
nltk                      3.9.1                    pypi_0    pypi
numpy                     1.26.4          py310h5f9d8c6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.26.4          py310hb5e798b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
omnigibson                1.1.1                    pypi_0    pypi
omniverse-kit             106.0.1.126909           pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-contrib-python     4.10.0.84                pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.0.15               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
orjson                    3.10.12                  pypi_0    pypi
osqp                      0.6.7.post3              pypi_0    pypi
packaging                 24.1            py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pandas                    2.2.3                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
patch                     2.7.6             h7b6447c_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
patchelf                  0.17.2               h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pcre2                     10.42                hebb0a14_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
perspective2d             1.0.0                     dev_0    <develop>
pexpect                   4.9.0                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2            py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pkginfo                   1.11.2          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
platformdirs              3.10.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
plotly                    5.24.1                   pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
portalocker               3.0.0                    pypi_0    pypi
progressbar               2.5                      pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
protobuf                  5.28.3                   pypi_0    pypi
psutil                    5.9.0           py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
py-lief                   0.12.3          py310h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pybind11-abi              4                    hd3eb1b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pycocotools               2.0.8                    pypi_0    pypi
pycosat                   0.6.6           py310h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pycparser                 2.21               pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pydantic                  2.10.2                   pypi_0    pypi
pydantic-core             2.27.1                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pyequilib                 0.3.0                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pymeshlab                 2022.2.post4             pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pyperclip                 1.9.0                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pytest                    8.3.3                    pypi_0    pypi
python                    3.10.15              he870216_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.9.0.post0              pypi_0    pypi
python-graphviz           0.20.3                   pypi_0    pypi
python-libarchive-c       5.1                pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-multipart          0.0.17                   pypi_0    pypi
pytz                      2024.1          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyyaml                    6.0.2           py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
qdldl                     0.1.7.post4              pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
referencing               0.30.2          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
regex                     2024.11.6                pypi_0    pypi
reproc                    14.2.4               h6a678d5_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
reproc-cpp                14.2.4               h6a678d5_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.32.3          py310h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
retrying                  1.3.4                    pypi_0    pypi
rich                      13.9.4                   pypi_0    pypi
robomimic                 0.3.0                     dev_0    <develop>
rpds-py                   0.10.6          py310h4aa5aa6_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
rtree                     1.2.0                    pypi_0    pypi
ruamel.yaml               0.18.6          py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ruamel.yaml.clib          0.2.8           py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ruff                      0.8.0                    pypi_0    pypi
s3transfer                0.10.4                   pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
sam-2                     1.0                      pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                75.1.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
shapely                   2.0.6                    pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
simsimd                   6.2.0                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.5             py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sqlite                    3.45.3               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
stack-data                0.6.3                    pypi_0    pypi
starlette                 0.41.3                   pypi_0    pypi
stringzilla               3.10.10                  pypi_0    pypi
supervision               0.25.0                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tenacity                  9.0.0                    pypi_0    pypi
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.9.20                pypi_0    pypi
timm                      1.0.11                   pypi_0    pypi
tk                        8.6.14               h39e8969_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tokenizers                0.20.4                   pypi_0    pypi
tomli                     2.0.1           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tomlkit                   0.12.0                   pypi_0    pypi
torch                     2.5.1                    pypi_0    pypi
torchvision               0.20.1                   pypi_0    pypi
tqdm                      4.66.5          py310h2f386ee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
traitlets                 5.14.3                   pypi_0    pypi
transformers              4.46.3                   pypi_0    pypi
transforms3d              0.4.2                    pypi_0    pypi
trimesh                   4.0.10                   pypi_0    pypi
triton                    3.1.0                    pypi_0    pypi
truststore                0.8.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
typer                     0.13.1                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
urllib3                   2.2.3           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
uvicorn                   0.32.1                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.6                    pypi_0    pypi
wheel                     0.44.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
widgetsnbextension        4.0.13                   pypi_0    pypi
xformers                  0.0.28.post3             pypi_0    pypi
xz                        5.4.6                h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.2.5                h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yaml-cpp                  0.8.0                h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yapf                      0.43.0                   pypi_0    pypi
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstandard                 0.23.0          py310h2c38b39_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstd                      1.5.6                hc292b87_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```

**Comment by cremebrule** [comment]
Hmmm I don't see anything glaringly obvious from that list.

I'm wondering if it's somehow due to your `chmod` call. Is there a reason you needed to do that? I don't think `chmod -R` recursively iterates through symbolic links so perhaps the underlying file the symbolic link was referencing didn't have its privileges changed, and so it wasn't accessible?

**Comment by Snowflake-Pink** [comment]
> Hmmm I don't see anything glaringly obvious from that list.
> 
> I'm wondering if it's somehow due to your `chmod` call. Is there a reason you needed to do that? I don't think `chmod -R` recursively iterates through symbolic links so perhaps the underlying file the symbolic link was referencing didn't have its privileges changed, and so it wasn't accessible?

@cremebrule Maybe🧐

I don't have a profound grasp of symbolic links, so I might not be able to offer more help with this issue. Thank you for your friendly reply!

**Comment by cremebrule** [comment]
Hi @Snowflake-Pink ,

Are you still running into issues? Or were you able to resolve the problem?

**Comment by Snowflake-Pink** [comment]
> I fixed it by copy sam2/configs /sam2/sam2_hiera_l.yaml to overwrite sam2/sam2_hiera_l.yaml (the Symbolic Link). 😐😐
> 
> I don't know why this link doesn't work. The only extra action I did is `chmod -R 777 digital-cousins` (All files of digital-cousins).

Hi @cremebrule ,

I runned successfully by doing the solution I used before👆. But I didn't test a reinstallation. And I am afraid I could not provide more information about this, since I have removed the environment before. Thank you for your kind help and this awesome project!

**Comment by cremebrule** [comment]
Hi @Snowflake-Pink ,

No worries -- glad you got it working! Hope digital cousins is serving you well (:
