### ISSUE TITLE
KeyError: 'ISAAC_PATH'

### ISSUE THREAD

**Issue by saulgooodman** [cremebrule/digital-cousins#27]
Hello, this is truly a remarkable piece of work!
I encountered an issue while trying to run the example (the problem occurred in step 3 of ACDC). Specifically, I ran into a problem when attempting to merge the cousins and create a new environment using Omniverse Isaac Sim:

```
                    ##################################################
                    ##################################################
                    # Running ACDC: Step 3 -- Simulated Scene Generation
                    ##################################################
                    ##################################################
                        
Generating simulated scenes given output ./input-simpler/acdc_output/step_2_output/step_2_output_info.json...


####################################################
####  Generating simulated scenes in OmniGibson ####
####################################################

####################################################
####  Generating simulated scenes in OmniGibson ####
####################################################

            
[INFO] [omnigibson.simulator] ----- Starting OmniGibson. This will take 10-30 seconds... -----
Traceback (most recent call last):
  File "/home/data0/fqy/digital-cousins-main/digital_cousins/pipeline/acdc.py", line 206, in <module>
    main(args)
  File "/home/data0/fqy/digital-cousins-main/digital_cousins/pipeline/acdc.py", line 174, in main
    pipeline.run(
  File "/home/data0/fqy/digital-cousins-main/digital_cousins/pipeline/acdc.py", line 162, in run
    success, step_3_output_path = step_3(
  File "/home/data0/fqy/digital-cousins-main/digital_cousins/pipeline/generation.py", line 188, in __call__
    og.launch()
  File "/home/data0/fqy/digital-cousins-main/OmniGibson/omnigibson/simulator.py", line 246, in _launch_simulator
    og.app = _launch_app()
  File "/home/data0/fqy/digital-cousins-main/OmniGibson/omnigibson/simulator.py", line 123, in _launch_app
    isaac_path = os.environ["ISAAC_PATH"]
  File "/root/anaconda3/envs/acdc/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'ISAAC_PATH'
```

Does this mean that I still need to install ISSACSIM and add ISSACSIM to the environment variables? Thank you!

**Comment by saulgooodman** [comment]
This issue is caused by the incorrect installation of Isaac Sim. It is recommended to first install Isaac Sim and configure the correct environment variables for it, then proceed with the installation of Digital Cousin. After doing so, you should no longer encounter such problems.

**Comment by chenhaomingbob** [comment]
Hello, I also have the same problem. I'm a beginner for Isaac. Could you please tell me if you installed Isaac following the https://github.com/isaac-sim/IsaacSim?tab=readme-ov-file#quick-start? And what version do you have?
